# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Alpen < Formula
  desc "Access log parser/encoder CLI"
  homepage "https://github.com/nekrassov01/alpen"
  version "0.0.18"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nekrassov01/alpen/releases/download/v0.0.18/alpen_Darwin_arm64.tar.gz"
      sha256 "cfabeff470dc31da917762f01ca752f3644aed79dc85586c850fab9db95c1454"

      def install
        bin.install "alpen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nekrassov01/alpen/releases/download/v0.0.18/alpen_Darwin_x86_64.tar.gz"
      sha256 "99b28f0c1eef10f80859fbea7f8e9d05fa0a058eaa320df5eeb7223e2dc5ea47"

      def install
        bin.install "alpen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nekrassov01/alpen/releases/download/v0.0.18/alpen_Linux_arm64.tar.gz"
      sha256 "eb67742d34f54a3595c1b5d0a432a44c2780a96abd8a4aaca1e0371c38b8e03c"

      def install
        bin.install "alpen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nekrassov01/alpen/releases/download/v0.0.18/alpen_Linux_x86_64.tar.gz"
      sha256 "62a0d7a0230a2e06ef6e1cecbb6ac8751a55942f5bd6239870cd3ccc5a079bc5"

      def install
        bin.install "alpen"
      end
    end
  end
end
