# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BacklogUtils < Formula
  desc "Backlog API utilities"
  homepage "https://github.com/nekrassov01/backlog-utils"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nekrassov01/backlog-utils/releases/download/v0.1.0/backlog-utils_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "f6eb3b50f35fff3b5ba43fdf40ee85b342012e7a9603546b70ca44e3c42e9fa5"

      define_method(:install) do
        bin.install "bkl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nekrassov01/backlog-utils/releases/download/v0.1.0/backlog-utils_0.1.0_Darwin_arm64.tar.gz"
      sha256 "b5de52fe62ae48094f9430daea15c8a534ff92435f508e094910ee68aa155047"

      define_method(:install) do
        bin.install "bkl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nekrassov01/backlog-utils/releases/download/v0.1.0/backlog-utils_0.1.0_Linux_x86_64.tar.gz"
      sha256 "6700fd453cc325dd18636a6c4fe60f6cd11059a767d177b899891317568fd44a"
      define_method(:install) do
        bin.install "bkl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nekrassov01/backlog-utils/releases/download/v0.1.0/backlog-utils_0.1.0_Linux_arm64.tar.gz"
      sha256 "aef4803915eef191eb7e0635ee143baaa66be7fee24c0b16c52e683ccc9dd2f7"
      define_method(:install) do
        bin.install "bkl"
      end
    end
  end
end
