# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bkl < Formula
  desc "Backlog utilities"
  homepage "https://github.com/nekrassov01/bkl"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nekrassov01/backlog-utils/releases/download/v0.0.1/bkl_Darwin_x86_64.tar.gz"
      sha256 "80531e6aa82cd5a6b3a918d82b0a4c16fc2a1516251784c0087ef6e2d0008742"

      def install
        bin.install "bkl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nekrassov01/backlog-utils/releases/download/v0.0.1/bkl_Darwin_arm64.tar.gz"
      sha256 "8523de96adb91f828baa2ac8176853c2170f01f187cbd26f13dfa43666d6b3e3"

      def install
        bin.install "bkl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nekrassov01/backlog-utils/releases/download/v0.0.1/bkl_Linux_x86_64.tar.gz"
        sha256 "5b7b11c5da6c079b9991e9e7f6e871dbcdad7e585645ea4db8608082f50a7ac5"

        def install
          bin.install "bkl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nekrassov01/backlog-utils/releases/download/v0.0.1/bkl_Linux_arm64.tar.gz"
        sha256 "1c8f16d6ffccbbdec964562407a0849c906126515fe96a60585c01ef8226fd59"

        def install
          bin.install "bkl"
        end
      end
    end
  end
end
