# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bkl < Formula
  desc "Backlog utilities"
  homepage "https://github.com/nekrassov01/bkl"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nekrassov01/backlog-utils/releases/download/v0.0.1/bkl_Darwin_x86_64.tar.gz"
      sha256 "39370163a6ce83a61d0aacffb7fbf05a191cd16d25721b66023a7354d577659d"

      def install
        bin.install "bkl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nekrassov01/backlog-utils/releases/download/v0.0.1/bkl_Darwin_arm64.tar.gz"
      sha256 "516c1ee024eb8071af519c51087f2ce4fa3f2fca4807f59e3d10d6c3d2361e98"

      def install
        bin.install "bkl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nekrassov01/backlog-utils/releases/download/v0.0.1/bkl_Linux_x86_64.tar.gz"
        sha256 "604eb93ef47811f1f10c050989cdbfaeaaa898ad1b60891161c5b312155db1de"

        def install
          bin.install "bkl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nekrassov01/backlog-utils/releases/download/v0.0.1/bkl_Linux_arm64.tar.gz"
        sha256 "f9978db9808896b957aeef7e7bd5cc650cd51eb010add9d3839ea22dd61f85f6"

        def install
          bin.install "bkl"
        end
      end
    end
  end
end
