# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bkl < Formula
  desc "Backlog utilities"
  homepage "https://github.com/nekrassov01/bkl"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nekrassov01/backlog-utils/releases/download/v0.0.1/bkl_Darwin_x86_64.tar.gz"
      sha256 "59fd0a7c68f69758f1df467eb30064972721b044e97800e6b2250dcaeaa8b170"

      def install
        bin.install "bkl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nekrassov01/backlog-utils/releases/download/v0.0.1/bkl_Darwin_arm64.tar.gz"
      sha256 "598d3ebbf74cc1dbcb3a561fa398570d56d9f5f52b9171f2d766ccad53a954dc"

      def install
        bin.install "bkl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nekrassov01/backlog-utils/releases/download/v0.0.1/bkl_Linux_x86_64.tar.gz"
        sha256 "6f098f49f0489f765306bc7e5b9a132ba8ee1c8016edc9030c0558237387f204"

        def install
          bin.install "bkl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nekrassov01/backlog-utils/releases/download/v0.0.1/bkl_Linux_arm64.tar.gz"
        sha256 "4ff2ccb5ac6539a8b3656937b192c05397ea27dd01b22b02ee8a84a942ce4ce6"

        def install
          bin.install "bkl"
        end
      end
    end
  end
end
