# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ignoresync < Formula
  desc "Your shadow repository for ignored files"
  homepage "https://github.com/nekrassov01/ignoresync"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nekrassov01/ignoresync/releases/download/v0.0.1/ignoresync_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "38e3b9458ed74f63db9a17e920fc3c39b20ea051e4b4f77bcc914ceaf1298eda"

      define_method(:install) do
        bin.install "ignoresync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nekrassov01/ignoresync/releases/download/v0.0.1/ignoresync_0.0.1_Darwin_arm64.tar.gz"
      sha256 "9f1f7454f71c608747216359a2cb5a5e33c6cb6dca5741f8c53931c43eb88570"

      define_method(:install) do
        bin.install "ignoresync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nekrassov01/ignoresync/releases/download/v0.0.1/ignoresync_0.0.1_Linux_x86_64.tar.gz"
      sha256 "33ab6209fbcbc2bcef8db7de36c0829a169d7ef919fbdf506103138f71195006"
      define_method(:install) do
        bin.install "ignoresync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nekrassov01/ignoresync/releases/download/v0.0.1/ignoresync_0.0.1_Linux_arm64.tar.gz"
      sha256 "040fea608e44b38c0d7148c2ab536c4015e9a15d7c05993ed84d2e9666e35bcb"
      define_method(:install) do
        bin.install "ignoresync"
      end
    end
  end
end
