# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ignoresync < Formula
  desc "Your shadow repository for ignored files"
  homepage "https://github.com/nekrassov01/ignoresync"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nekrassov01/ignoresync/releases/download/v0.0.1/ignoresync_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "fca6188d98df4d1d359a550749a8c6c57662ae833bffe540af35ac2878393ffc"

      define_method(:install) do
        bin.install "ignoresync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nekrassov01/ignoresync/releases/download/v0.0.1/ignoresync_0.0.1_Darwin_arm64.tar.gz"
      sha256 "a501847f3501de85bd3c519a8e8124388c130daed8a8ff5df11142f7d7be99a6"

      define_method(:install) do
        bin.install "ignoresync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nekrassov01/ignoresync/releases/download/v0.0.1/ignoresync_0.0.1_Linux_x86_64.tar.gz"
      sha256 "a6db88514620d031dfa0fa3f40ca9ae6cafe42abdd5ebef717c4f27c6cdc2f89"
      define_method(:install) do
        bin.install "ignoresync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nekrassov01/ignoresync/releases/download/v0.0.1/ignoresync_0.0.1_Linux_arm64.tar.gz"
      sha256 "2474fdf1c0b2588367940b73d1cf73e0dec5d80784e486cfac02211355ab04cb"
      define_method(:install) do
        bin.install "ignoresync"
      end
    end
  end
end
