# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lem < Formula
  desc "The env splitting, delivery, replacement, and monitoring tool for monorepo"
  homepage "https://github.com/nekrassov01/lem"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nekrassov01/lem/releases/download/v0.0.1/lem_Darwin_x86_64.tar.gz"
      sha256 "6eb859ea032e2351c8f607c8d5ea1c9d51f245dd58b6f8ef2b465461ae79b919"

      def install
        bin.install "lem"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nekrassov01/lem/releases/download/v0.0.1/lem_Darwin_arm64.tar.gz"
      sha256 "e7260158a95e814752abe97f8e14d5a413424f96755ec836c2fa7889f5c598d4"

      def install
        bin.install "lem"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/nekrassov01/lem/releases/download/v0.0.1/lem_Linux_x86_64.tar.gz"
      sha256 "6ee48e93db72f907d7618dd5ecc7ec2c43136b32bd811ab3c41e556fe106e8f3"
      def install
        bin.install "lem"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/nekrassov01/lem/releases/download/v0.0.1/lem_Linux_arm64.tar.gz"
      sha256 "69acd496bfc1c99c41820dad068d001ae005830d4dec928fc0b4ee2d52ea3d5a"
      def install
        bin.install "lem"
      end
    end
  end
end
