# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lem < Formula
  desc "The env splitting, delivery, replacement, and monitoring tool for monorepo"
  homepage "https://github.com/nekrassov01/lem"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nekrassov01/lem/releases/download/v0.0.1/lem_Darwin_x86_64.tar.gz"
      sha256 "25f079de664980e5cdf3a761fe25683036feb7193b81f453991f633874966d52"

      def install
        bin.install "lem"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nekrassov01/lem/releases/download/v0.0.1/lem_Darwin_arm64.tar.gz"
      sha256 "c3012135ae65928df90f3d8acb869d8de6e8738ea49681914e8f46466f59b7d7"

      def install
        bin.install "lem"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/nekrassov01/lem/releases/download/v0.0.1/lem_Linux_x86_64.tar.gz"
      sha256 "a30293d6356bfefbf0ffa47f76e18f0e4f478f5536648cfbe3eb588c250ca07b"
      def install
        bin.install "lem"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/nekrassov01/lem/releases/download/v0.0.1/lem_Linux_arm64.tar.gz"
      sha256 "4044e56f61336044d21534d22acfffa3c97a536f4c12b581e6851eea34023cbf"
      def install
        bin.install "lem"
      end
    end
  end
end
