# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Llcm < Formula
  desc "AWS log groups lifecycle manager"
  homepage "https://github.com/nekrassov01/llcm"
  version "0.0.15"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nekrassov01/llcm/releases/download/v0.0.15/llcm_Darwin_x86_64.tar.gz"
      sha256 "76b4f7787ad5713342bb568cfb386856a0b3108aea5c5fd5cae19a93bedd277f"

      def install
        bin.install "llcm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nekrassov01/llcm/releases/download/v0.0.15/llcm_Darwin_arm64.tar.gz"
      sha256 "da08d892e4e9bb79a234e18369a0b7acde78c3d4fa296fda3024cd3f744987ed"

      def install
        bin.install "llcm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nekrassov01/llcm/releases/download/v0.0.15/llcm_Linux_x86_64.tar.gz"
        sha256 "25fb0505597256e5022aea2f38fd9628d0d7bda93aa5eebfcdae1fb711110ef5"

        def install
          bin.install "llcm"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nekrassov01/llcm/releases/download/v0.0.15/llcm_Linux_arm64.tar.gz"
        sha256 "02644168cd2c94e3bbda764cf1f50b4757d25bb9064fefac6110f941dd58b83c"

        def install
          bin.install "llcm"
        end
      end
    end
  end
end
