# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Llcm < Formula
  desc "AWS log groups lifecycle manager"
  homepage "https://github.com/nekrassov01/llcm"
  version "0.0.27"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nekrassov01/llcm/releases/download/v0.0.27/llcm_Darwin_x86_64.tar.gz"
      sha256 "ef9f2a2c7bb6332ecee49e8e40a59d32a3ea6746d53f07b5e54230fed55fbdaa"

      def install
        bin.install "llcm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nekrassov01/llcm/releases/download/v0.0.27/llcm_Darwin_arm64.tar.gz"
      sha256 "db457067c0c66e0d07c921f4aea21741199a5af049501eb964388b3cb2e3ce68"

      def install
        bin.install "llcm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nekrassov01/llcm/releases/download/v0.0.27/llcm_Linux_x86_64.tar.gz"
      sha256 "35d8e540fdb63dea5fc9fb2ecc8e8c5288a9baa0fa1c32fc8a49da95e7683e47"
      def install
        bin.install "llcm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nekrassov01/llcm/releases/download/v0.0.27/llcm_Linux_arm64.tar.gz"
      sha256 "6a35b5d979e3f3b112ad15f3dbb13bf1071a220377974013d7cee69e05ca9883"
      def install
        bin.install "llcm"
      end
    end
  end
end
