# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3bytes < Formula
  desc "S3 size checker CLI"
  homepage "https://github.com/nekrassov01/s3bytes"
  version "0.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nekrassov01/s3bytes/releases/download/v0.0.6/s3bytes_Darwin_x86_64.tar.gz"
      sha256 "fa1d9a9609dd60b4a8c19788b786ff76828044a0f08c5cc34cd3a5f9dd38202c"

      def install
        bin.install "s3bytes"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nekrassov01/s3bytes/releases/download/v0.0.6/s3bytes_Darwin_arm64.tar.gz"
      sha256 "565efe575ec16eb5f4b1f57258814a76b50e9dc3bcd36ce49b2e4d6167113acd"

      def install
        bin.install "s3bytes"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nekrassov01/s3bytes/releases/download/v0.0.6/s3bytes_Linux_x86_64.tar.gz"
        sha256 "f18abe565bebcf803ef3695e6a11e214140f04680dc67e074c03229dfa4ab33d"

        def install
          bin.install "s3bytes"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nekrassov01/s3bytes/releases/download/v0.0.6/s3bytes_Linux_arm64.tar.gz"
        sha256 "b4dace94ffb6e9b25b5e7e0a115f231ae2cf7868ab83caa19d9a05f276fda6c1"

        def install
          bin.install "s3bytes"
        end
      end
    end
  end
end
