# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3bytes < Formula
  desc "S3 size checker CLI"
  homepage "https://github.com/nekrassov01/s3bytes"
  version "0.0.18"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nekrassov01/s3bytes/releases/download/v0.0.18/s3bytes_Darwin_x86_64.tar.gz"
      sha256 "c49b0c9e8c2716350ad196801d0646c7a881702d15eae8f4130c35908402def5"

      def install
        bin.install "s3bytes"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nekrassov01/s3bytes/releases/download/v0.0.18/s3bytes_Darwin_arm64.tar.gz"
      sha256 "df2d7c9d6c9a3e733c19d64fc024feb7cfe7492b217ee60fb38e26b2b2a3e399"

      def install
        bin.install "s3bytes"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nekrassov01/s3bytes/releases/download/v0.0.18/s3bytes_Linux_x86_64.tar.gz"
      sha256 "6a908a5f3b1b8b987f1c0d2b0453986149e2e83da64aa7de2efe32610d71f1a9"
      def install
        bin.install "s3bytes"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nekrassov01/s3bytes/releases/download/v0.0.18/s3bytes_Linux_arm64.tar.gz"
      sha256 "af3b12b41d6b204500fe1f29c097e9840165a02f4a595b48bd2e8f6579ab5cf8"
      def install
        bin.install "s3bytes"
      end
    end
  end
end
